name: service-containers
on:
  push:
    branches:
      - "main"
jobs:
  container-job:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    env:
      DATABASE_NAME: my-database
      DATABASE_USER: foo-user
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DATABASE: ${{ env.DATABASE_NAME }}
          POSTGRES_USER: ${{ env.DATABASE_USER }}
    steps:
      - name: Install psql client
        run: apt-get -y update && apt-get -y install postgresql-client dnsutils
      - name: Run dns utils
        run: nslookup postgres && dig postgres
      - name: Connect to PostgreSQL
        run: psql -U ${{ env.DATABASE_USER }} -d ${{ env.DATABASE_NAME }} -h postgres -c 'select * from information_schema.tables;'