name: service-containers
on:
  push:
    branches:
      - "main"
jobs:
  container-job:
    runs-on: ubuntu-latest
    env:
      DATABASE_NAME: my_database
      DATABASE_USER: foo_user
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ${{ env.DATABASE_NAME }}
          POSTGRES_USER: ${{ env.DATABASE_USER }}
    steps:
      - name: Install psql client
        run: sudo apt-get -y update && sudo apt-get -y install postgresql-client dnsutils
      - name: Connect to PostgreSQL
        run: psql -U ${{ env.DATABASE_USER }} -d ${{ env.DATABASE_NAME }} -h localhost -c 'select * from information_schema.tables;'
